name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        if: success()
        run: go test -cover ./... -coverprofile=coverage.txt -covermode=atomic
